// swiftlint:disable line_length
// Generated by desktop/design/style-dictionary.config.mjs from desktop/design/tokens (`just desktop-tokens`). Do not edit.
// swift-format-ignore-file

import SwiftUI

/// A text style (DS§3.2): points at 100 % text size, line height as a multiple, tracking in em.
public struct FontToken: Sendable, Hashable {
    public let size: CGFloat
    public let weight: Font.Weight
    public let design: Font.Design
    public let lineHeight: CGFloat
    public let tracking: CGFloat
}

/// One shadow layer of an elevation level (DS§3.4); an inset layer is the top-edge highlight.
public struct ShadowLayer: Sendable, Hashable {
    public let color: Color
    public let x: CGFloat
    public let y: CGFloat
    public let blur: CGFloat
    public let spread: CGFloat
    public let inset: Bool
}

/// An elevation level (DS§3.4): its shadow layers, bottom first.
public struct ElevationToken: Sendable, Hashable {
    public let layers: [ShadowLayer]
}

public enum Space {
    public static let xxs: CGFloat = 2
    public static let xs: CGFloat = 4
    public static let s: CGFloat = 6
    public static let m: CGFloat = 8
    public static let ml: CGFloat = 10
    public static let l: CGFloat = 12
    public static let xl: CGFloat = 16
    public static let xxl: CGFloat = 20
    public static let xxxl: CGFloat = 24
    public static let huge: CGFloat = 32
}

public enum Radius {
    public static let xs: CGFloat = 4
    public static let s: CGFloat = 6
    public static let m: CGFloat = 8
    public static let l: CGFloat = 10
    public static let xl: CGFloat = 12
    public static let xxl: CGFloat = 14
    public static let panel: CGFloat = 16
    public static let pane: CGFloat = 18
    public static let popover: CGFloat = 20
    public static let window: CGFloat = 22
    /// Badges and inline code: the mockup's border-radius 5px, between xs and s
    public static let badge: CGFloat = 5
    public static let capsule: CGFloat = 999
}

public enum Size {
    public static let toolbarHeight: CGFloat = 56
    public static let sidebarWidth: CGFloat = 252
    public static let inspectorWidth: CGFloat = 324
    public static let readingWidth: CGFloat = 760
    public static let paneGap: CGFloat = 8
    public static let capsuleHeight: CGFloat = 32
    public static let buttonHeight: CGFloat = 28
    public static let buttonHeightSmall: CGFloat = 24
    public static let iconTile: CGFloat = 22
    public static let statusDot: CGFloat = 9
    /// The glow around a live StatusDot: the mockup's 0 0 0 3px ring of the soft status colour
    public static let statusDotHalo: CGFloat = 3
    /// An idle StatusDot's ring: the mockup's border 1.5px
    public static let statusDotRing: CGFloat = 1.5
    /// CountBadge's height and least width: the mockup's .cnt line-height 16px
    public static let countBadge: CGFloat = 16
    public static let hairline: CGFloat = 0.5
    /// A quote's bar in the transcript (A97), coloured quote.bar
    public static let quoteBar: CGFloat = 3
    public static let windowMinWidth: CGFloat = 1100
    public static let windowMinHeight: CGFloat = 700
    public static let popoverWidth: CGFloat = 340
    public static let tokenPopoverWidth: CGFloat = 360
}

public extension FontToken {
    /// Session title in the toolbar
    static let titleWindow = FontToken(size: 13.5, weight: .semibold, design: .default, lineHeight: 1.3, tracking: 0)
    /// Default UI text
    static let body = FontToken(size: 13, weight: .regular, design: .default, lineHeight: 1.45, tracking: 0)
    /// Assistant and user messages
    static let transcript = FontToken(size: 13.5, weight: .regular, design: .default, lineHeight: 1.55, tracking: 0)
    /// Level-1 Markdown headings in the transcript (DT§5.9, A94)
    static let transcriptH1 = FontToken(size: 17, weight: .semibold, design: .default, lineHeight: 1.35, tracking: 0)
    /// Level-2 Markdown headings in the transcript (DT§5.9, A94)
    static let transcriptH3 = FontToken(size: 15, weight: .semibold, design: .default, lineHeight: 1.35, tracking: 0)
    /// Level-3 Markdown headings in the transcript, and levels 4-6, which DT§5.9 does not size (A94)
    static let transcriptH4 = FontToken(size: 13, weight: .semibold, design: .default, lineHeight: 1.35, tracking: 0)
    /// Buttons, capsules, segmented items
    static let control = FontToken(size: 12.5, weight: .medium, design: .default, lineHeight: 1.2, tracking: 0)
    /// Thinking line, notices
    static let caption = FontToken(size: 12, weight: .regular, design: .default, lineHeight: 1.4, tracking: 0)
    /// Tool status, meter, key-value rows
    static let footnote = FontToken(size: 11.5, weight: .regular, design: .default, lineHeight: 1.4, tracking: 0)
    /// Uppercase section headers
    static let label = FontToken(size: 11, weight: .semibold, design: .default, lineHeight: 1.3, tracking: 0.03)
    /// Key caps, legends, badges
    static let micro = FontToken(size: 10.5, weight: .medium, design: .default, lineHeight: 1.3, tracking: 0)
    /// Big numbers (tok/s); tabular digits
    static let metric = FontToken(size: 26, weight: .semibold, design: .default, lineHeight: 1, tracking: -0.02)
    /// Code blocks, diffs
    static let monoCode = FontToken(size: 12, weight: .regular, design: .monospaced, lineHeight: 1.55, tracking: 0)
    /// Inline code in prose
    static let monoInline = FontToken(size: 12, weight: .regular, design: .monospaced, lineHeight: 1.3, tracking: 0)
    /// Terminal tail
    static let monoTerminal = FontToken(size: 11.5, weight: .regular, design: .monospaced, lineHeight: 1.5, tracking: 0)
}

public extension ElevationToken {
    /// Flat: transcript prose, collapsed tool rows
    static let e0 = ElevationToken(layers: [])
    /// Chips, capsules, icon tiles, selected row
    static let e1 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.1), x: 0, y: 1, blur: 2, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.08), x: 0, y: 4, blur: 10, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.95), x: 0, y: 1, blur: 0, spread: 0, inset: true),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.55), x: 0, y: 0, blur: 0, spread: 0.5, inset: true),
    ])
    /// Cards: user bubble, expanded tool, sidebar, inspector
    static let e2 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.1), x: 0, y: 2, blur: 4, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.14), x: 0, y: 10, blur: 26, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.95), x: 0, y: 1, blur: 0, spread: 0, inset: true),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.55), x: 0, y: 0, blur: 0, spread: 0.5, inset: true),
    ])
    /// Composer: the one thing that floats highest in a pane
    static let e3 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.14), x: 0, y: 4, blur: 10, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.26), x: 0, y: 24, blur: 60, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.95), x: 0, y: 1, blur: 0, spread: 0, inset: true),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.55), x: 0, y: 0, blur: 0, spread: 0.5, inset: true),
    ])
    /// Popovers and menus
    static let e4 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.17), x: 0, y: 8, blur: 20, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 25 / 255, green: 30 / 255, blue: 80 / 255, opacity: 0.33), x: 0, y: 30, blur: 70, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1), x: 0, y: 1, blur: 0, spread: 0, inset: true),
    ])
    /// The window over the wallpaper
    static let e5 = ElevationToken(layers: [
        ShadowLayer(color: Color(.sRGB, red: 8 / 255, green: 10 / 255, blue: 40 / 255, opacity: 0.3), x: 0, y: 16, blur: 40, spread: 0, inset: false),
        ShadowLayer(color: Color(.sRGB, red: 8 / 255, green: 10 / 255, blue: 40 / 255, opacity: 0.55), x: 0, y: 50, blur: 120, spread: 0, inset: false),
    ])
}

public enum Motion {
    /// Hover, press
    public static let durationFast: TimeInterval = 0.12
    /// Disclosure expand/collapse
    public static let durationBase: TimeInterval = 0.2
    /// Popover, sheet, pane slide
    public static let durationSlow: TimeInterval = 0.32
    /// Most transitions
    public static let easingStandard: UnitCurve = .bezier(startControlPoint: UnitPoint(x: 0.2, y: 0), endControlPoint: UnitPoint(x: 0, y: 1))
    /// Things entering
    public static let easingDecelerate: UnitCurve = .bezier(startControlPoint: UnitPoint(x: 0, y: 0), endControlPoint: UnitPoint(x: 0.2, y: 1))
}

public enum MaterialToken {
    public static let frostedWindowOpacity: Double = 0.42
    public static let frostedBlur: Double = 34
    public static let frostedSaturation: Double = 1.9
    public static let frostedSpecular: Double = 0.35
    public static let glossyWindowOpacity: Double = 0.3
    public static let glossyBlur: Double = 6
    public static let glossySaturation: Double = 1.9
    public static let glossySpecular: Double = 0.55
    public static let solidWindowOpacity: Double = 1
    public static let solidBlur: Double = 0
    public static let solidSaturation: Double = 1
    public static let solidSpecular: Double = 0
    public static let readableFloorWindowOpacity: Double = 0.8
    public static let highContrastGlassKeep: Double = 0.25
    /// Dark mode, `dark_highlight = none`: no top-edge highlight, the dark mockup's look (A109)
    public static let darkHighlightNone: Double = 0
    /// Dark mode, `dark_highlight = subtle`: the highlight at this share of the light one's strength (A109)
    public static let darkHighlightSubtle: Double = 0.1
}

// swiftlint:enable line_length
