[package]
name = "cox-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cox-protocol = { path = "../cox-protocol", version = "0.1.0" }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
