//! Hand-written to match `migrations/00000000000001_init/up.sql` exactly
//! (plan.md §1.7/D9: "`schema.rs` is generated by `diesel print-schema`
//! and committed [...] a test asserts it matches the migrations"). Written
//! by hand here rather than via the `diesel_cli` binary; `schema_snapshot_matches`
//! (lib.rs) compares the live `sqlite_master` SQL against a committed insta
//! snapshot, so drift between this file and the DDL still fails a test even
//! without the generator.
//!
//! FTS5 virtual tables (`memory_fts`, `rollout_fts`) have no `table!` entry:
//! Diesel cannot model `VIRTUAL TABLE`, so they are created in `up.sql` and
//! queried through `diesel::sql_query` + `QueryableByName` instead (D9).

diesel::table! {
    /// App-level migration ledger declared in the DDL (plan.md §1.7).
    /// Unused by `diesel_migrations`, which tracks its own bookkeeping table;
    /// no `cox-store` code reads or writes this yet.
    migrations (version) {
        version -> Integer,
        applied_at -> Text,
    }
}

diesel::table! {
    sessions (id) {
        id -> Text,
        created_at -> Text,
        updated_at -> Text,
        cwd -> Text,
        project_slug -> Text,
        title -> Nullable<Text>,
        parent_id -> Nullable<Text>,
        rollout_path -> Text,
        turns -> Integer,
        cost_usd -> Double,
        state -> Text,
    }
}

diesel::table! {
    usage (id) {
        id -> Integer,
        session_id -> Text,
        turn -> Integer,
        job -> Text,
        tier -> Text,
        provider -> Text,
        model -> Text,
        input_tokens -> BigInt,
        output_tokens -> BigInt,
        cache_read_tokens -> BigInt,
        cache_write_tokens -> BigInt,
        estimated -> Bool,
        cost_usd -> Double,
        latency_ms -> BigInt,
        context_tokens -> BigInt,
        created_at -> Text,
        effort -> Nullable<Text>,
    }
}

diesel::table! {
    archive (id) {
        id -> Text,
        session_id -> Text,
        call_id -> Text,
        tool -> Text,
        subject -> Nullable<Text>,
        bytes -> BigInt,
        sha256 -> Text,
        inline -> Nullable<Binary>,
        path -> Nullable<Text>,
        created_at -> Text,
    }
}

diesel::table! {
    memory (id) {
        id -> Integer,
        project_slug -> Text,
        name -> Text,
        path -> Text,
        kind -> Text,
        updated_at -> Text,
    }
}
