#!/bin/bash
# Copyright (c) 2026 Ivan Tugay
# SPDX-License-Identifier: GPL-3.0-only
# Licensed under GPL-3.0 only; see https://www.gnu.org/licenses/gpl-3.0.html

#
# Print the Homebrew cask for one cox release.
#
#   scripts/cask.sh <version> <sha256-aarch64> <sha256-intel>
#
# The release workflow writes the output to Casks/cox.rb in pyrlyn/homebrew-tap
# on every release, so the file there is generated, never edited by hand: change
# this script instead.

set -euo pipefail

if [ $# -ne 3 ]; then
  echo "usage: $0 <version> <sha256-aarch64> <sha256-intel>" >&2
  exit 2
fi

VERSION="${1#v}"
SHA_ARM="$2"
SHA_INTEL="$3"

for sha in "$SHA_ARM" "$SHA_INTEL"; do
  if ! printf '%s' "$sha" | grep -Eq '^[0-9a-f]{64}$'; then
    echo "not a sha256: $sha" >&2
    exit 2
  fi
done

cat <<EOF
# Generated by scripts/cask.sh in pyrlyn/cox on every release. Do not edit:
# the next release overwrites this file. Change scripts/cask.sh instead.
cask "cox" do
  arch arm: "aarch64", intel: "x86_64"

  version "${VERSION}"
  sha256 arm:   "${SHA_ARM}",
         intel: "${SHA_INTEL}"

  url "https://github.com/pyrlyn/cox/releases/download/v#{version}/cox-#{arch}-apple-darwin.tar.xz"
  name "cox"
  desc "Modular terminal coding agent"
  homepage "https://github.com/pyrlyn/cox"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  # cox installs into ~/.local/bin via install.sh; Homebrew only delivers the
  # tarball. Nothing is linked into the prefix.
  stage_only true

  postflight do
    set_ownership "\#{staged_path}/cox"
  end

  uninstall delete: "\#{staged_path}/cox"

  zap trash: "~/.cox"
end
EOF